### ISSUE TITLE
`process.hrtime.bigint` does not exist in browsers

### ISSUE THREAD

**Issue by Richienb** [BluSpring/java-util-random#1]
This functionality needs to be shimmed, polyfilled or replaced for browsers:

https://github.com/BluSpring/java-util-random/blob/f491097b411f49034a509533474b8cfa2eb6dff7/src/index.ts#L20

https://github.com/BluSpring/java-util-random/blob/f491097b411f49034a509533474b8cfa2eb6dff7/src/index.ts#L30

**Comment by BluSpring** [comment]
I never intended for this module to be used in browsers, so if you wish you can fork this module for browser usage, otherwise you can just use the [java-random](https://www.npmjs.com/package/java-random) module. This was just made with the sole intention of having typings and BigInt-based seeds.
