### ISSUE TITLE
The npm distribution of java-util-random is missing the main Random class.

### ISSUE THREAD

**Issue by atengel** [BluSpring/java-util-random#2]
Hello! Just wanted to mention that the npm distribution of this package does not contain the index.ts file and thus the main Random class, so is unusable in its current form. Thanks so much for taking the time to implement this package!

https://www.npmjs.com/package/java-util-random

**Comment by BluSpring** [comment]
this is what happens when you write code when you're young and dumb.

i just fixed it. you can update to 1.0.2, thanks for letting me know pfft.

**Comment by atengel** [comment]
Hah I know the feeling! Thanks so much for the quick follow up!
